# -*- coding: utf-8 -*-
"""Drug_Addiction_Analysis (2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_Y21KVTDRvNf2ifZHLnhh2q8wYefaQU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/lab f1143/Social_Media_Impact_OnStudents.csv')

df.head()

df.shape

df.isnull().sum()

sns.heatmap(df.isnull())

import math
modeTestScore1=(df['UsageLimitation'].mode()[0])

df['UsageLimitation']=df['UsageLimitation'].fillna(modeTestScore1)

df.isnull().sum()

sns.heatmap(df.isnull())

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

categorical_columns = [
    'AgeGroup', 'Gender', 'SocialMediaHours', 'UsageDuringStudy',
    'FocusReduction', 'Procrastination', 'CheckingDuringStudy',
    'CourseworkDistraction', 'TimeManagementDifficulty',
    'NotificationDisruption', 'Multitasking', 'TimeLost', 'StudyDelay',
    'UsageLimitation', 'AcademicImpact', 'ProductivityWithoutSM',
    'MostUsedPlatform', 'BreakFrequency', 'ProductivityImpact'
]

for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

df.head()

"""# **DATA ANALYSIS**"""

df.info()

df.describe()

plt.figure(figsize=(8, 6))
sns.boxplot(data=df, orient='h')
plt.title("Box Plot of DataFrame")
plt.show()

# prompt: drop timestamp

if "Timestamp" in df.columns:
    df.drop(columns=["Timestamp"], inplace=True)
else:
    print("Column 'Timestamp' not found in DataFrame, skipping drop operation.")

df.corr()

plt.figure(figsize=(18,15))
sns.heatmap(df.corr(), annot=True,fmt=".2f")
plt.title("Correlation Matrix Heatmap")
plt.show()

"""# **DATA SPLITING**"""

import pandas as pd
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
categorical_columns = df.select_dtypes(include=['object']).columns

encoder = LabelEncoder()
for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

X_numeric = df[numeric_columns].drop(columns=['ProductivityImpact'])
y = df['ProductivityImpact']

selector = SelectKBest(score_func=chi2, k=8)

X_numeric_new = selector.fit_transform(X_numeric, y)

selected_indices = selector.get_support(indices=True)

selected_features = X_numeric.columns[selected_indices]
print("Selected Features:")
print(selected_features)

from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X_numeric_new, y, test_size=0.2, random_state=42)

print("Training data shape (X_train, y_train):", X_train.shape, y_train.shape)
print("Testing data shape (X_test, y_test):", X_test.shape, y_test.shape)

"""**NAIVE_BAYES** **MODEL**"""

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix
cm = np.array(pd.crosstab(y_test, y_pred))
sns.heatmap(cm, annot=True, fmt=".2f")
plt.xlabel("True Label")
plt.ylabel("Predicted Label")
plt.title("Confusion Matrix for Naive Bayes Classifier")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""**DECESSION** **TREE**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt=".2f")
plt.xlabel("True Label")
plt.ylabel("Predicted Label")
plt.title("Confusion Matrix for Decision Tree Classifier")
plt.show()

"""**KNN**"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

cm = np.array(pd.crosstab(y_test, y_pred))
sns.heatmap(cm, annot=True, fmt=".2f")
plt.xlabel("True Label")
plt.ylabel("Predicted Label")
plt.title("Confusion Matrix for KNN Classifier")
plt.show()

"""**LOGISTIC REGRESSION**"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = np.sum(y_pred == y_test) / len(y_test)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

cm = np.array(pd.crosstab(y_test, y_pred))
sns.heatmap(cm, annot=True, fmt=".2f")

plt.xlabel("True Label")
plt.ylabel("Predicted Label")
plt.title("Confusion Matrix for Logistic Regression Classifier")
plt.show()

"""**LINEAR REGRESSION**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MAE:", mae)
print("MSE:", mse)
print("R^2:", r2)

!pip install streamlit pyngrok scikit-learn joblib pandas